### ISSUE TITLE
Issue with `doctrine/persistence` v3

### ISSUE THREAD

**Issue by darthf1** [liip/LiipTestFixturesBundle#182]
Hi!

When I upgrade `doctrine/persistence` from v2 to v3, suddenly the following error start to popup:
```
Error: Call to undefined method Doctrine\Bundle\DoctrineBundle\Mapping\ClassMetadataFactory::getCacheDriver()
/builds/0/app/api/vendor/liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php:44
/builds/0/app/api/tests/Functional/FixtureTestCase.php:37
/builds/0/app/api/tests/Functional/Infrastructure/Shared/Doctrine/Migrations/DoctrineMigrationTest.php:25
/builds/0/app/api/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/builds/0/app/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/builds/0/app/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/builds/0/app/api/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/builds/0/app/api/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
```

From the persistence [upgrade guide](https://github.com/doctrine/persistence/blob/3.0.x/UPGRADE.md):
```
BC Break: removed support for doctrine/cache

Removed support for using doctrine/cache for metadata caching. The setCacheDriver and getCacheDriver methods have been removed from Doctrine\Persistence\Mapping\AbstractMetadata. Please use getCache and setCache with a PSR-6 implementation instead.
```

Does this mean this library should have a direct dependency on `doctrine/persistence`? For now I added a `conflict` on `"doctrine/persistence": ">=3.0.0",` in my `composer.json`.

**Comment by alexislefebvre** [comment]
We may had a compatibility layer in order to call `getCache()` if it's available, or `getCacheDriver()` otherwise.

**Comment by magnetik** [comment]
The new `getCache()` method in `AbstractClassMetadataFactory` in now protected (and was public)

**Comment by mbabker** [comment]
This one's fun.

Based on https://github.com/liip/LiipFunctionalTestBundle/pull/69 the intent is to flush the result cache before loading fixtures, but it's pulling the cache driver from the object manager's metadata factory.  Only the ORM has a result cache though.  Making things even more inconsistent, the ORM entity manager configures the metadata factory with the metadata cache service, which might not even be the same service as the result cache service.  The document managers for MongoDB and PHPCR are also injecting the metadata cache service.

So if the intent is to clear the result cache, as the original PR implies, then there is a long-standing bug that needs to be fixed in the `ORMDatabaseTool` and it needs to pull the correct cache service from the entity manager's configuration instance and the `MongoDBDatabaseTool` and `PHPCRDatabaseTool` classes can have this cache clearing operation removed.

If the intent is to clear the metadata cache, then the way forward looks to be replacing the `getMetadataFactory()` calls with `getConfiguration()` (note, that method isn't part of the `ObjectManager` interface) and fetching the metadata cache service from there.

**Comment by MarkPedron** [comment]
> If the intent is to clear the metadata cache, then the way forward looks to be replacing the `getMetadataFactory()` calls with `getConfiguration()` (note, that method isn't part of the `ObjectManager` interface) and fetching the metadata cache service from there.

I prepared a MR which implements this suggestion - the property `$om` is annotated as an `EntityManager` in `ORMDatabaseTool`, so the fact that `getConnection` is not part of the `ObjectManager` interface does not seem to be an issue here.

I do not have much experience with the doctrine caching system, but this PR makes the tests in my projects run.

_Edit_

This only fixes the issue for ORMDatabaseTool, not MongoDB/PHPCR/ORMSqlite

**Comment by alexislefebvre** [comment]
Please try the last release: https://github.com/liip/LiipTestFixturesBundle/releases/tag/2.4.0
