### ISSUE TITLE
API Stability

### ISSUE THREAD

**Issue by tarjei** [liip/LiipTestFixturesBundle#202]
Ok, heres a complaint more than a feature request.
 
While I understand that you were not fond of using a Trait to load fixtures I would like to note that this bundle has provided way too much churn in our tests due to changes in how one thinks it is nice to write tests. We have followed Liip's test fixtures bundle for almost 10 year in our projects now and the main reason we wait with upgrading to a new symfony version is not SFs API changes but the amount of churn we get from LiipTestFixtures bundle.

Test libraries should have more stable APIs than you have managed to provide with this bundle over the years. Was it necessary to change the API and removing the TestFixture trait in (#18)  or could you have provided guidance for the new API and just kept the old way of doing things without removing the code?

I know this is an open source project and I understand that I'm getting something for free, but as a long time user I just wanted to make you aware of the pain you are causing with API churn - both removing FixturesTrait and now having to load fixtures after makeClient() are major changes that should not be needed.

Regards,
Tarjei

**Comment by tarjei** [comment]
I'm closing this. I think it might be a bit harsh.

**Comment by alexislefebvre** [comment]
Thanks for sharing your thoughts.

> Test libraries should have more stable APIs than you have managed to provide with this bundle over the years. Was it necessary to change the API and removing the TestFixture trait in (https://github.com/liip/LiipTestFixturesBundle/issues/18) or could you have provided guidance for the new API and just kept the old way of doing things without removing the code?

I prefer the new API because it's more explicit than the trait. And it was causing issues when using the trait from this bundle and the trait from LiipFunctionalTestBundle, see https://github.com/liip/LiipFunctionalTestBundle/issues/535

Yet keeping the trait for Backward Compatibility is an interesting idea. Feel free to open a PR to restore `FixturesTrait` in order to plug it to the new API. It may require some glue like this trait that provide the container to several versions of Symfony: https://github.com/liip/LiipTestFixturesBundle/blob/2.x/tests/Traits/ContainerProvider.php

> now having to load fixtures after makeClient() are major changes that should not be needed.

You should be able to load fixtures after booting the kernel, I use the following code to test some commands, `makeClient()` is not called. So you should be able to load fixtures before calling `makeClient()`.

<details>
<summary>The base class: <code>tests/Command/Base.php</code></summary>

```php
<?php

declare(strict_types=1);

namespace App\Tests\Command;

use Liip\TestFixturesBundle\Services\DatabaseToolCollection;
use Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class Base extends KernelTestCase
{
    public Application $application;

    public CommandTester $commandTester;

    public AbstractDatabaseTool $databaseTool;

    protected function setUp(): void
    {
        self::bootKernel();

        $container = self::$kernel->getContainer();
        /** @var DatabaseToolCollection $dbToolCollection */
        $dbToolCollection = $container->get(DatabaseToolCollection::class);
        $this->databaseTool = $dbToolCollection->get();

        $this->application = new Application(static::$kernel);
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        unset($this->databaseTool);
    }
}
```
</details>


<details>
<summary>One test: <code>tests/Command/CommandTest.php</code></summary>

```php
<?php

declare(strict_types=1);

namespace App\Tests\Command;

use Symfony\Component\Console\Tester\CommandTester;

class CommandTest extends Base
{
    public CommandTester $commandTester;

    protected function setUp(): void
    {
        parent::setUp();

        $command = $this->application->find('project:command');
        $this->commandTester = new CommandTester($command);
    }

    public function testCalculateBadgesScoreCommand(): void
    {
        $this->databaseTool->loadFixtures([
            'App\DataFixtures\ORM\LoadUserSiteBadgeData',
        ]);

        $this->commandTester->execute([]);

        $this->assertSame(0, $this->commandTester->getStatusCode());

        $display = $this->commandTester->getDisplay();

        $this->assertStringContainsString('Done.', $display);
    }
}
```
</details>
