### ISSUE TITLE
[question] Using one database state for all tests

### ISSUE THREAD

**Issue by jazithedev** [liip/LiipTestFixturesBundle#204]
Hello 👋,

I want to ask if there's a way of executing all fixtures at the beginning before running tests, and getting access to all fixture references in particular tests?

(using Symfony 6)

Thanks in advance!

**Comment by alexislefebvre** [comment]
Hello :wave:,
do you want to load fixtures only once before running tests, or before running each test? This bundle was designed for loading fixtures before each test.

For loading fixtures only once, you may be able to load the fixtures before running your test, and use [DAMADoctrineTestBundle](https://github.com/dmaicher/doctrine-test-bundle) so that the database is not altered by the tests (the transaction will revert the changes automatically).

**Comment by jazithedev** [comment]
Yes, want to load fixtures only once before running tests 🙂. Currently I'm doing that with help of a separate Symfony bootstrap file, but that makes me not being able to access created fixture references unfortunately at the level of tests. Trying to figure it out whether there's a way to it 😁. But I'm assuming it's not possible with this bundle.

**Comment by alexislefebvre** [comment]
This bundle load the fixtures and return them: https://github.com/liip/LiipTestFixturesBundle/blob/39cd702d97f1df3b40994c4b98aada8822307dd3/tests/Test/ConfigMysqlTest.php#L98-L114

Alternatively, you can access to the fixtures during the tests by using an id, email, etc. in order to fetch the fixtures you want. As long as you have access to the repository of your entity, you can fetch it.

**Comment by jazithedev** [comment]
Ok! Thank you @alexislefebvre for your help 🙂.
